In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]],columns=['cgpa','profile_score','placed'])

In [4]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [5]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

In [7]:
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[-0.85135615,  0.34804618],
        [-0.65368724,  1.0459307 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[8.2180846e-01],
        [7.4279308e-04]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
new_weights = [
    np.array([[0.1,0.1],[0.1,0.1]], dtype='float32'),
    np.array([0.,0.] , dtype='float32'),
    np.array([[0.1],[0.1]], dtype='float32'),
    np.array([0.1] , dtype='float32'),
]

In [16]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [17]:
model.set_weights(new_weights)

In [19]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.1], dtype=float32)]

In [22]:
optimize = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimize,loss='binary_crossentropy')

In [23]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.7652
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7368
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7359
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7185
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7183
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6423
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7354
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6844
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7342
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7589
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6845
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6845
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6845
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6684
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6844 
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━

In [24]:
model.get_weights()

[array([[0.10916556, 0.10916556],
        [0.02856043, 0.02856043]], dtype=float32),
 array([-0.03637476, -0.03637476], dtype=float32),
 array([[0.06907781],
        [0.06907781]], dtype=float32),
 array([0.06678423], dtype=float32)]